containers:
  - name: dotnet-api
    image: ghcr.io/adamovick/kral-blog:v5

    env:
      - name: DB_HOST
        value: postgres

      - name: DB_PORT
        value: "5432"

      - name: DB_NAME
        value: postgres

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USER

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD

    ports:
      - containerPort: 8080