apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../apps/dotnet-api/base

images:
  - name: ghcr.io/adamovick/platform-demo-api
    newTag: 46a07cf6930112241af68be189ab30340a8cde62

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
