apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../apps/dotnet-api/base

images:
  - name: ghcr.io/adamovick/platform-demo-api
    newTag: 3a7ec2d22d13de5c07d69b5a5809f723c79e81d8

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
