---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dotnet-api-dev-secret
  namespace: dev
spec:
  encryptedData:
    ApiKey: AgA5P4+CdRZkz7SfRhRQdcpWy79Gbn0pbJYPj2vNad87uFeHjErBkY8rNk1n67mfx1795+hf9iw4Jv0FesS1rU4Ok14D/XOA6oP8s5y5HPB9litlSX592fzCzGNDqrjWFcal/AUMKaLZ30iDRq6pg2zC16HDJ31dysUeSLhmVUIBhvJmn9nn8GyguvdfG/bgffTALb9p6S4w8UhdH9it/KPStq4GEr/B5U6jrEBlZvwQwwqUJ5BaVwjzBDZjZmf0Sdiz+dF0NqiKsYi9UWDz7VsuW5cbIjdLsk3n4Q8f6J/ve+25cuorXmoLYSdjPGBSDeTyjUMG+zjC7nFoXtySBOngtMdm/6uOmmTIA36En1jThKt1jU1WB8hVb1icKFmzXWDl6sRlf4figQkB4TY4UgqnCw8pc70vvn4eY2HsVbKr4fKW+GoVIeOFTvYezLyOrM3MaDFT5dT9FCRRXpituu7lkKIxsi9rcQ22zcncXq6TpD0xT2Z1KRD/7ntAyWI1kw6n/45LlTwAmnsUA3DfXH7zBfhgfy7/2R5MkI5dsjSKIRrUVi8M3QvBOx0QUw9TcvEZo/N04jFGHEKx7rZHMcyFkj427eqi61ZNSTeTBv7/6kIs4oOaft5I908N4We2ZsTtnpsHdom4Br8/AslG/k1vYHORNA92fVL++9sFnywwwRtqjvb9N4kygSvjo48qzzUIg33wy48/2GCTVAvY5jGw
    DbPassword: AgAlnv5+wLSnAeNMjt+HznETY9qGBcycqp8EYRScJA3x/k2+Cw/GsVPMt3JnMTUIItinJNGYA4hJFTMlyuQkKCYDw8WgF+PwChOhk9wfUzVcjHt6772Sp7zZVpPbVUzlY6LGCDAZbPw/Pr+4dlsBAiaab0Fuw0NfdsEcJUvRNwnTONiFeEDI+BPV/T3c3kmGU12/2TG1yjq/fLc9dfS84iDaf4lRjFWbJKf/D2pAalkzpk7tKP+BIrIIo2Ps3kovpiyDesydkJAVnDNMstvfvTcVDIA4HDlNWTxUcPnqvua5bc7W6iugznHcr0mK4519J72fRx6HxK2wYVbuS3i/vaHjZO6PpW5sLQyNkNxLxoV/0vEds8x2FOpm0E/O+Fv1IbzEfK9dYOqGOxm8hwqPdMqU4dWNcJGIrrXeQiju93c1yytgNL+UB44/MDJSXFQc5KBOZWyCnrT7AG4anMycMv2NaNUy5tWM8tZtSNURn0K9WUMyMR1flM9c1eh05CNtZIn+EojNKUBNCk+obR9D2zE5AdeEVEfQgkTT9UfzPGEUc8JRIhcqPayCuXSF6CaaLMvqVTwCed8Qmxzj8vIwMjT2mEXL/Hon5V2kg8XhBjM0eOWnczo+tYj+aFNfz99kFGUj5WeLcpb92QFID8VuoJe5O2OuCup7x/GRB1JRFZR6ciHLwaVTsvY3+IOipw9jukXZ7SuQiZWEXwoplpnaKzMLKyv8Gkl9qAu0kUi5yKuBrg==
  template:
    metadata:
      name: dotnet-api-dev-secret
      namespace: dev
    type: Opaque
