resources:
  - ../../../apps/dotnet-api/base

namespace: stage

namePrefix: stage-

images:
  - name: ghcr.io/adamovick/platform-demo-api
    newTag: 6a837691a87c492558a71439ab10ff3e42719fb8

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
