apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-api-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/adamovick/platform-lab-gitops.git
    targetRevision: main
    path: environments/test/dotnet-api

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
